version: "3.6"

services:
  postgres:
    image: "postgres:11-alpine"
    environment:
      - "POSTGRES_DB=bgjournal"
      - "POSTGRES_USER=postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - persistence

  bgjournal:
    image: "bgjournal/api"
    ports:
      - "8000:8000"
    volumes:
      - "./files/bgjournal/settings.py:/bg-journal/bgjournal/settings.py"
    depends_on:
      - postgres
    networks:
      - persistence

networks:
  persistence: {}

volumes:
  postgres-data: {}
